# Generated by Django 4.2 on 2026-07-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_book_discount_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBNConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='978', max_length=3)),
                ('digit_length', models.PositiveSmallIntegerField(default=10)),
                ('current_sequence', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'isbn_config',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='book',
            name='final_price',
        ),
        migrations.AddField(
            model_name='book',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre-order'), ('coming_soon', 'Coming Soon')], default='in_stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
