# Generated by Django 4.2 on 2026-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_isbnconfig_remove_book_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
