# Generated by Django 4.2 on 2026-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_book_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default='2026-02-15'),
            preserve_default=False,
        ),
    ]
