# Generated by Django 4.2 on 2026-07-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('HI', 'Hindi'), ('EN', 'English'), ('UR', 'Urdu')], default='HI', max_length=50),
        ),
    ]
