# Generated by Django 4.2 on 2026-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_publisher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
