# Generated by Django 4.2 on 2026-07-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_publisher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='author_profile/'),
        ),
    ]
