# Generated by Django 4.2 on 2026-08-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetils',
            name='cm_gender',
            field=models.CharField(max_length=20),
        ),
    ]
