# Generated by Django 4.2 on 2026-08-28 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0002_alter_personaldetils_cm_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetils',
            name='cm_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetils',
            name='cm_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer Not To Say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personaldetils',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile/'),
        ),
        migrations.AlterField(
            model_name='personaldetils',
            name='user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
