# Generated by Django 4.2 on 2026-07-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_address_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'OrderItem'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='user_address',
        ),
        migrations.AlterModelTable(
            name='order',
            table='user_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='book_order_item',
        ),
    ]
